# Generated by Django 6.0.2 on 2026-02-27 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(default="Description TBA")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "editors",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"role": "Editor"},
                        related_name="editor_publishers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journalists",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"role": "Journalist"},
                        related_name="journalist_publishers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_publisher",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "readers",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"role": "Reader"},
                        related_name="reader_publishers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
